// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'Icon:akarIcons:arrowRight': typeof import('~icons/akar-icons/arrow-right')['default']
    'Icon:akarIcons:codepenFill': typeof import('~icons/akar-icons/codepen-fill')['default']
    'Icon:akarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'Icon:akarIcons:linkedinBoxFill': typeof import('~icons/akar-icons/linkedin-box-fill')['default']
    'Icon:akarIcons:moonFill': typeof import('~icons/akar-icons/moon-fill')['default']
    'Icon:akarIcons:sunFill': typeof import('~icons/akar-icons/sun-fill')['default']
    'Icon:akarIcons:twitterFill': typeof import('~icons/akar-icons/twitter-fill')['default']
    'Icon:bi:filetypeSql': typeof import('~icons/bi/filetype-sql')['default']
    'Icon:mdi:vuetify': typeof import('~icons/mdi/vuetify')['default']
    'Icon:teenyicons:cSharpSolid': typeof import('~icons/teenyicons/c-sharp-solid')['default']
    'Icon:teenyicons:css3Solid': typeof import('~icons/teenyicons/css3-solid')['default']
    'Icon:teenyicons:firebaseSolid': typeof import('~icons/teenyicons/firebase-solid')['default']
    'Icon:teenyicons:html5Solid': typeof import('~icons/teenyicons/html5-solid')['default']
    'Icon:teenyicons:javascriptSolid': typeof import('~icons/teenyicons/javascript-solid')['default']
    'Icon:teenyicons:mongodbSolid': typeof import('~icons/teenyicons/mongodb-solid')['default']
    'Icon:teenyicons:nodejsSolid': typeof import('~icons/teenyicons/nodejs-solid')['default']
    'Icon:teenyicons:nuxtjsSolid': typeof import('~icons/teenyicons/nuxtjs-solid')['default']
    'Icon:teenyicons:tailwindSolid': typeof import('~icons/teenyicons/tailwind-solid')['default']
    'Icon:teenyicons:typescriptSolid': typeof import('~icons/teenyicons/typescript-solid')['default']
    'Icon:teenyicons:vueSolid': typeof import('~icons/teenyicons/vue-solid')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
