// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    'Icon:akarIcons:codepenFill': typeof import('~icons/akar-icons/codepen-fill')['default']
    'Icon:akarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'Icon:akarIcons:linkedinBoxFill': typeof import('~icons/akar-icons/linkedin-box-fill')['default']
    'Icon:akarIcons:twitterFill': typeof import('~icons/akar-icons/twitter-fill')['default']
    'Icon:mdi:at': typeof import('~icons/mdi/at')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
