// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dado: typeof import('./src/components/prototypes/dado.vue')['default']
    Eva: typeof import('./src/components/prototypes/eva.vue')['default']
    FigmaLogo: typeof import('./src/components/prototypes/figmaLogo.vue')['default']
    GameboyCss: typeof import('./src/components/prototypes/gameboyCss.vue')['default']
    'Icon:akarIcons:codepenFill': typeof import('~icons/akar-icons/codepen-fill')['default']
    'Icon:akarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    'Icon:akarIcons:linkedinBoxFill': typeof import('~icons/akar-icons/linkedin-box-fill')['default']
    'Icon:akarIcons:twitterFill': typeof import('~icons/akar-icons/twitter-fill')['default']
    'Icon:heroiconsOutline:externalLink': typeof import('~icons/heroicons-outline/external-link')['default']
    'Icon:mdiDownload': typeof import('~icons/mdi/download')['default']
    KrilinSticker: typeof import('./src/components/prototypes/krilinSticker.vue')['default']
    RickCard: typeof import('./src/components/prototypes/rickCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
